### ISSUE TITLE
Upgrade to pylexibank 2.x

### ISSUE THREAD

**Issue by chrzyki** [lexibank/sagartst#1]

**Comment by xrotwang** [comment]
@LinguList can we re-license this as CC-BY?

**Comment by LinguList** [comment]
yes, will do now.

**Comment by xrotwang** [comment]
@LinguList I'm about to upgrade this. So I'll just add CC-BY as license, ok?

**Comment by xrotwang** [comment]
@LinguList The URL in `raw/data.json` doesn't work anymore - and possibly is not supposed to work? I guess, we should simply disable `cmd_download`?

**Comment by LinguList** [comment]
Yes, I just checked it as well. The URL in metadata.json is also broken, since I re-arranged the thins on my server for edictor.

**Comment by LinguList** [comment]
But this URL in RAW data is easy to modify.

Although I'd also say: if one wants a new version, this is a new dataset.

**Comment by LinguList** [comment]
Okay, at least the URL in raw data is fixed. If not leaving it there, I'd add it to a NOTES.md field to make sure people can still retrieve the languages in there.

**Comment by xrotwang** [comment]
Running download and makecldf again changes `forms.csv` - mostly because `cogid`s changed, but also some segmentations are different. Should we stick to the data in `raw` as it was for the first release, or is it ok if this is evolving?

**Comment by LinguList** [comment]
@xrotwang, are you planning on upgrading this? Otherwise, I'd have a pass later, since the handling of the "profile" should be incorporated in the script, following our discussions, etc.

**Comment by xrotwang** [comment]
At least I started upgrading. Can push the current status and let you take over.

**Comment by LinguList** [comment]
Ah, we should stick to the old version, as this means some of the collaborators changed the data again, but we would like to reflect the version in the publication.

**Comment by LinguList** [comment]
Okay, let me do it, as I have a plan to get rid of the multiple internal things (clean up my own mess...)

**Comment by xrotwang** [comment]
ok. will push in a sec.

**Comment by xrotwang** [comment]
done
